apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-docker-producer-v2
  namespace: springboot-application
  labels:
   app: siddhuproducer
   version: v2
spec:
  selector:
    matchLabels:
      component: siddhuproducer
      version: v2
  template:
    metadata:
      labels:
        component: siddhuproducer
        version: v2
    spec:
      containers:
      - name: siddhuproducer
        image: shdhumale/springboot-docker-producer:latest
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 8091
          name: http
          protocol: TCP