apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-docker-producer-v1
  namespace: springboot-application
  labels:
   app: siddhuproducer
   version: v1
spec:
  selector:
    matchLabels:
      component: siddhuproducer
      version: v1
  template:
    metadata:
      labels:
        component: siddhuproducer
        version: v1
    spec:
      containers:
      - name: siddhuproducer
        image: shdhumale/springboot-docker-producer:latest
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 8091
          name: http
          protocol: TCP      
---

apiVersion: v1
kind: Service
metadata:
  name: siddhuproducer
  namespace: springboot-application
  labels:
    service: siddhuproducer
spec:
  type: NodePort
  selector:
    component: siddhuproducer
  ports:
  - name: http
    port: 8091
    targetPort: 8091